version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
    - ./_knowledge:/usr/share/elasticsearch/data
#   - ./knowledge_base:/usr/share/elasticsearch/data
      # - ./knowledge_base_:/usr/share/elasticsearch/data
#      - ./esdata:/usr/share/elasticsearch/data

    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  kibana:
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge